### ISSUE TITLE
Multiple Databases?

### ISSUE THREAD

**Issue by zolrath** [danecando/hapi-sequelize#32]
If I need to access two databases in my application one could normally assign sequelize to two variables, assigning a database to each. 

Since the hapi-sequelized plugin is accessed via `request.server.plugins['hapi-sequelized']` is there a way to register this plugin twice and access it via different keys?

**Comment by danecando** [comment]
I want to find out if anyone has an opinion on the best way to handle this. There's a couple different ways that stick out in my mind...

**A**: Allow the plugin to be registered multiple times.

* **Ideas**:
	* Decorate the server instance with a method for getting specific DB instances (stored somewheres in a map/hash or smth) which contain the registered models.
	* Just simply map them to the plugin object based on an index provided like a name
	
* **Pros**:
	* Get the benefits of the default setup / init during plugin regsitrations.

* **Cons**:
	* Will need to check for other instances of the plugin being registered and possibly break out of it's little plugin bubble a bit.

**B**: Register the plugin once and provide an interface for creating new DB instances.

* **Pros**: 
	* A clean interface for managing your DB connections & models.
	* DB's / model's can be added to the application at any point.
* **Cons**:
	* DB's / model's would most likely be setup after plugin registration (which typically happens right before the server starts) *Unless we accept an array of option objects and just perform the setup like that. We could still provide the same interface for more flexibility anyways*.

So anyways, if you guys have any other ideas or opinions on this one please feel free to add them here! I want to put out a new and improved version of the plugin. :)

**Comment by luthv** [comment]
Option B most likely provides a more flexible way, perhaps the plugin can provide some kind of factory function where we can register the db option objects with named key, and then use a lazy load to create the actual db object when the db key name is accessed the first time.

**Comment by danecando** [comment]
Here's what I've come up with for v3

````javascript
const options = [{
  name: 'instance-name',
  models: ['path/one', 'path/two'],
  instance: new Sequelize(config),
  debug: true
}]
````

Keep it simple let the user create their Sequelize instances and pass them into the plugin config. Plugin will sync up models w/ each instance, make them available throughout the server instance(s), and provide whatever small API necessary to get the jerb done. 

Let me know if you guys have any thoughts on this. Working on it now, shouldn't take long. Going to probably only support node LTS >= and the latest versions of Hapi & Sequelize will be targeted.

**Comment by danecando** [comment]
done
