### ISSUE TITLE
check compatibility with hapi 10+

### ISSUE THREAD

**Issue by danecando** [danecando/hapi-sequelize#33]

**Comment by Nargonath** [comment]
That's probably not enough as "test" but I use this package with Hapi 12.1 at the moment and everything works fine so far.

**Comment by danecando** [comment]
Thanks. So if the last release has been compatible up to 12+ that's perfect. I'm developing 3 now with the latest in mind but I don't see any breaking changes that would cause it to not work in previous versions as well.
