### ISSUE TITLE
where should I put beforeBulkSync/afterBulkSync declaration?

### ISSUE THREAD

**Issue by zachguo** [danecando/hapi-sequelize#36]
It's like following when not using `hapi-sequelized` (adapted from [here](https://github.com/sequelize/sequelize/issues/4479))
```
// executed "after" `sequelize.sync(...)`
sequelize.addHook('afterBulkSync', function (options) {
  // this = sequelize instance
  // create stored procedures here ...
})
```

What's the best place to put above codes when using `hapi-sequelized`? Is it possible to put this piece of codes in a model definition file? Thanks!

**Comment by danecando** [comment]
@zachguo 

Sorry about the late response I didn't notice a few of these new issues. 

```
var db = server.plugins['hapi-sequelize'].db;
db.sequelize.sync().then(function() {
  console.log('models synced');
});
```

You could just put it in the promise after the sync if that's when the hook is executed

**Comment by zachguo** [comment]
thx
