### ISSUE TITLE
Error in loading model does not halt execution

### ISSUE THREAD

**Issue by danielrhodes** [danecando/hapi-sequelize#37]
When there is an issue with a model, such as a syntax error, there is only a light and undescriptive warning coming from sqlizr after it is loaded, due to this pull request:

https://github.com/mikefrey/sqlizr/commit/a2ec57a0b75cd4902f7749f8fb48e28b10dbe772.

My expectation is that I shouldn't be able to start the server if there is an error with one of the models, as that means the application behavior would almost definitely become unpredictable when certain models are available and others are not.

Maybe you have different reasoning, in which case perhaps some sort of promise on sqlizr and a config option on hapi-sequelize changing this behavior would be better.

**Comment by danecando** [comment]
@danielrhodes this was intended but I see your point. I will keep this in mind for the new updates
