### ISSUE TITLE
Testing without database connection

### ISSUE THREAD

**Issue by Nargonath** [danecando/hapi-sequelize#38]
**This is just a question.**

I just wrote a unit test suite where I check the integrity of my models (password should not be < 8 etc.) but I have to perform a database connection on each test therefore my test are pretty slow (~350ms).

Here is an example of a basic test:

``` javascript

'use strict';

var assert = require('assert');

var config = require('../../config/config');

var Hapi = require('hapi');

describe('User module: [model]', function() {
  var server = {};

  beforeEach('Setting up the server', function() {
    server = new Hapi.Server();
    server.connection();

    return server.register({
      register: require('hapi-sequelize'),
      options: {
        database: config.get('/database/credentials').dbName,
        user: config.get('/database/credentials').user,
        pass: config.get('/database/credentials').pass,
        dialect: config.get('/database/credentials').dialect,
        port: config.get('/database/credentials').port,
        models: 'app/modules/user/model.js',
        logging: false
      }
    })
    .then(function() {
      var db = server.plugins['hapi-sequelize'].db;

      return db.sequelize.sync({force: true})
                        .then(function() {
                          return server.initialize();
                        });
    })
    .catch(assert.ifError);
  });

  afterEach('Clear database/server connection', function() {
    server.plugins['hapi-sequelize'].db.sequelize.close();
    return server.stop();
  });

  describe('User model', function() {

    it('should hash user\'s password', function() {
      var User = server.plugins['hapi-sequelize'].db.sequelize.models.User;

      return User.create({
        email: 'test@gmail.com',
        password: 'iamapassword'
      })
      .then(function(user) {
        assert.equal(user.password.length, 60);
      })
      .catch(assert.ifError);
    });
  });
});
```

Is it possible to test Model creation without actually using a database connection? Is it possible to mock it or something alike?

**Comment by danecando** [comment]
I'm not sure. I need to make some updates to the plugin I'll look into this

**Comment by Nargonath** [comment]
Alright. Feel free to ask if you need some help. ;) I'll be happy to help if there is anything I can do.

**Comment by danecando** [comment]
https://github.com/sequelize/sequelize/issues/5645

**Comment by Nargonath** [comment]
Thanks for the link. I'll try to summarize what are the options in order to achieve what we want:

1. Use an in-memory SQLite database (doesn't remove the need of a database connection but speed up the communication).

2. Mocking sequelize.query() to return a promise.

As of these 2 options, I don't think there is something we can do in relation to your plugin, or at least I don't see what. Is your "enhancement" label still relevant? Did you have something in mind?

If there is something you wish to implement I'll be happy to help.

**Comment by danecando** [comment]
@Nargonath I think it's going to be more of a sequelize specific issue. I'm about update the plugin so that it's only job is hooking up your sequelize instances to hapi and sync'ing up models. Plugin options will accept an array of sequelize instance(s) and a couple options like model paths. Seems unnecessary to handle creating the instances in the plugin like it does right now.

**Comment by Nargonath** [comment]
I haven't forgotten about this issue, I just don't have the time atm to get into it but I hope I will soon. :)

**Comment by danecando** [comment]
@Nargonath  I just pushed an initial rewrite to the v3 branch. Will need some love and updates but I think we can make it work. Going to start fixing it up a bit and writing tests soon. Any suggestions welcome.

**Comment by danecando** [comment]
Maybe we can switch the tests over to sqlite instead of mysql to make this easier?

**Comment by Nargonath** [comment]
Hey sorry for not being active as I wanted to. The last months have been pretty harsh on me and I didn't have the time for OSS as I wished. 

I haven't really dived into your v3 rewrite but, if we can't free ourselves from an actual database, sqlite seems a good option. I saw that you moved the sequelize instanciation out of your plugin. Perhaps there is a way we could mock up sequelize instance now so we wouldn't actually require a real database for the tests. I remember reading something about it somewhere. I'll see if I can find it back. Not sure if you were talking about your own module's tests or people's tests using your module. :)
