### ISSUE TITLE
Support for mssql named instance

### ISSUE THREAD

**Issue by ngcammayo** [danecando/hapi-sequelize#40]
Hi,

How to add support for named instance on mssql?

Regards.

**Comment by danecando** [comment]
@ngcammayo what do you mean named instance? Having multiple mysql db's in the project?

**Comment by danecando** [comment]
Ah, I guess not. I don't have the slightest clue about mssql. Can you fill me in a little bit more so I can hopefully support this in the new version if necessary ?

**Comment by ngcammayo** [comment]
Hi, i was referring on the database instance i.e. localhost\\sqlexpress2014. The connection string seems to be invalid when using named instance. For now as a quick solution, I already re-installed the database server and use the default instance.

**Comment by danecando** [comment]
See comment in #42 - v3 api should solve this
