### ISSUE TITLE
Merge version 3 branch with master?

### ISSUE THREAD

**Issue by traducer** [danecando/hapi-sequelize#45]
The version on npm is currently 3.0.1. I was getting errors and couldn't figure out why. Just checked and saw master is not updated with npm's current version.

**Comment by traducer** [comment]
woops nevermind, just saw there was a v3 branch and it's currently in beta, disregard this

**Comment by luckycadow** [comment]
I just had the same problem.  I don't know how "beta" it can be when it's what you get with an `npm install hapi-sequelize` right now.

**Comment by danecando** [comment]
sry gang
