### ISSUE TITLE
sqlite dialect is not supported

### ISSUE THREAD

**Issue by saurabhghewari** [danecando/hapi-sequelize#49]
I am using hapi-sequelize in my project. working fine with mysql dialect in development and production mode, but sqlite dialect is not working properly. It does not create .sqlite file when specified in options.

    server.register(
        [
            {
                register: require('hapi-sequelized'),
                options: {
                    dialect: 'sqlite',
                    storage: "test.sqlite",
                    models: 'models/**/*.js',
                    sequelize: {
                        define: {
                            underscoredAll: true
                        }
                    }
                }
            },
        ], function(err) {
            if (err) {
                console.error('failed to load plugin');
            }
        }
    );

the above config options does not create sqlite file. can you help me where i am going wrong.

**Comment by danecando** [comment]
Please update to the new version
