### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by kreig303** [danecando/hapi-sequelize#50]
EDIT:  TBH I think I need to rethink the implementation and when I have a chance I'll check this out on my own.  Obviously what I have works so this was just gravy.  :-)

Hi,

Attempting to implement via confidence in an app, and when I attempt to add the plugin I get:

RangeError: Maximum call stack size exceeded

Research suggests its something to with having the dialectOptions set (necessary to encrypt with Azure SQL)...

          plugin: {
            register: 'hapi-sequelize',
            options: {
              name: 'mydb', 
              models: './server/models/**/*.js',
              sequelize: new Sequelize('DBNAME', 'username', 'password', {
                  host: 'xxx.database.windows.net', dialect: 'mssql', pool: {
                    max: 5,
                    min: 0,
                    idle: 10000
                  }, dialectOptions: {
                    encrypt: true
                  }
              }), // sequelize instance
            }
          }

I have started digging through your code and may try a fix myself if needed.

**Comment by TangMonk** [comment]
same problem

**Comment by kreig303** [comment]
Turns out a workaround is devised in #64.  Just noticed now while looking through issues as I look to use this plugin again.
