### ISSUE TITLE
Add test coverage

### ISSUE THREAD

**Issue by andela-rekemezie** [danecando/hapi-sequelize#60]
- [x] Add test coverage report to help contributors maintain good coverage.

- [x] Add test coverage badge to repo.

This issue would help #57 to be effective moving forward.
If this makes sense @danecando, I can take it.

**Comment by danecando** [comment]
@andela-rekemezie that's the goal. Write some tests, report coverage, and hook back up to travis for CI. If you want to help that would be fantastic. I'm going to push an update in the next few hours to have the project ready and not in this half assed beta / pre-release state that I left it.

**Comment by andela-rekemezie** [comment]
@danecando Waiting for you to update the repo. I noticed some decisions around assertion and testing libraries. Was there any reason you prefer `lab` to `mocha`?
I have some automation task set up already but for coverage, I thinking of mocha but wants to have you take because I don't know the decision around this.

**Comment by danecando** [comment]
Sorry for the delay.. @andela-rekemezie Hapi has it's own nice little ecosystem of tools and that includes the Lab testing framework and Code assertion lib. In my experience they are both great and have everything needed for a simple project. One thing that is nice to note about core hapi ecosystem projects is they typically only depend on other core hapi lib/modules so you don't end up having this out of control dependency graph. You know what you're getting. I added a general test in there to start but the Lab readme is pretty detailed. Let me know if I can help with anything in specific! Thanks

**Comment by andela-rekemezie** [comment]
Thanks @danecando

**Comment by andela-rekemezie** [comment]
@danecando could you please add the repo to coveralls.
