### ISSUE TITLE
confidence/glue support

### ISSUE THREAD

**Issue by kenhowardpdx** [danecando/hapi-sequelize#64]
Passing the sequelize instance in the options does not work with [confidence](https://github.com/hapijs/confidence) and [glue](https://github.com/hapijs/glue) as the composer requires the manifest to be valid JSON.

**Comment by danecando** [comment]
I'm vaguely familiar with glue. It sounds like there isn't much we can do about that besides going back to having the plugin manage building up the Sequelize instance during registration again. Is this the case or are there any work arounds?

**Comment by kenhowardpdx** [comment]
That's precisely the case, depending on `hapi-sequelize` to create the instance. What are the cons to having `Sequelize` be a core dependency?

**Comment by danecando** [comment]
That's how the plugin used to work before I did a complete rewrite (v3). Too tired to try and come up with a list of cons right now but my goal was to decouple Sequelize from the plugin and just make the plugin a lot simpler and more flexible overall. 

I have no interest in going back to that at this moment but I will take a look at this issue later and weigh the options

**Comment by kenhowardpdx** [comment]
The work around is registering an internal plugin that in-turn registers `hapi-sequelize`.

**./server/app-start/hapi-sequelize/index.js:**
```
import database from '../../database';

export const register: any = function register(server, options, next) {
    server.register({
        register: require('hapi-sequelize'),
        options: [
            {
                name: 'db',
                models: ['./server/models/**/*.js'],
                sequelize: database,
                sync: true
            }
        ]
    });

    next();
};

register.attributes = {
    name: 'sequelize',
    version: '1.0.0'
};
```

**./server/database/index.js:**
```
// libs
import * as Sequelize from 'sequelize';

export default new Sequelize(process.env.DB_DATABASE, process.env.DB_USER, process.env.DB_PASSWORD, {
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    dialect: process.env.DB_DIALECT,
    dialectOptions: {
        encrypt: true
    }
});
```

**./server/manifest.js:**
```
// libs
import {Store} from 'confidence';

let store: Store,
    manifest: any;

manifest = {
    $meta: 'server setup',
    connections: [...],
    registrations: [
        // Third Party Plugins
        ...
        {
            plugin: {
                register: './app-start/hapi-sequelize'
            }
        }
        ...
    ]
};

store = new Store(manifest);
```

**Comment by alexdrans** [comment]
@kenhowardpdx 

Can't you just do...

```
let manifest = require('./config/manifest');

manifest.registrations[10].plugin.options = {
    "name": "oo",
    "models": 'models/models/*.js',
    "sequelize": new Sequelize(process.env.DATABASE_URL, {
    }),
    "sync": true,
    "forceSync": false
  };
```

This loads the module correctly for me.
