### ISSUE TITLE
Does not register as a plugin

### ISSUE THREAD

**Issue by ADumaine** [danecando/hapi-sequelize#69]
I have tried many ways to get this module to register properly with no success.  It can be found under server.registrations, but does not appear in server.plugins.

My project uses glue/confidence with its composer.  It started with frame (https://github.com/jedireza/frame) which uses mongodb and the goal was to port it to postgres using hapi-sequelize

I have used the previous version of hapi-sequelize in an older project successfully so am familiar with it.  But in this new version having to instantiate the Sequelize object and pass it as an option is a challenge when using a manifest.

This project also uses pg and pg-pool so I know the connectivity to postgres works.

Tried the following:
 

-  followed https://github.com/danecando/hapi-sequelize/issues/64 (rewritten to not use typescript) and put it in the manifest.  Many variations: register first, last, etc. (a non-typescript version would be helpful - I'd post mine but it does not work).
-  putting the code in preRegistrations
-  putting the code in the server.js just before the server starts.
-  was using node 4.6, upgraded to 6.9.
-  did an npm rebuild

I must be missing something, but I am the point where I can't afford to spend any more time on it and have to start coding this in sql using pg directly.  Any hints or help is very much appreciated.

This is my latest attempt at implementing.  When inspecting the server it shows under server.registrations and appears to be correct.  It does not show up under plugins.
```
'use strict';
const Composer = require('./index');
var  Config = require('./config');

Composer((err, server) => {
    if (err) {
        throw err;
    }
    //try registering hapi-sequelize here
        var sq = require('sequelize');   
        var Seq =  new sq(process.env.PGDATABASE, process.env.PGUSER, process.env.PGPASSWORD, {
                        host: process.env.PGHOST,
                        port: process.env.PGPORT,
                        dialect: 'postgres'});
       
        server.register({
            register: require('hapi-sequelize'),
            options: 
                {
                    name: process.env.PGDATABASE,
                    models: Config.get('/hapiSequelize/models'),
                    sequelize: Seq,
                    sync: true,
                    debug: true
                }                
        }
        );
//check for hapi-sequelize
console.log(server.plugins)

    //init any associations before starting server
    var db = server.plugins['hapi-sequelize'].db;
    var Models = db.sequelize.models;

    var Account = Models.Account;
    Account.associate(Models);
   
    db.sequelize.sync().then(function () {
             console.log("models synced. ignore 'not a valid model' warnings");
        server.start(() => {
            console.log('Started the app on port ' + server.info.port);
        });
    });
});
```
Is there some sort of conflict between modules?  currently installed:
```
frame@12.0.0 C:\Data\Novo\gatewayserver
├── async@2.1.2
├── bcrypt@0.8.7
├── boom@4.1.0
├── code@3.0.2
├── confidence@3.0.2
├── debug@2.2.0
├── dotenv@2.0.0
├── glue@4.0.0
├── handlebars@4.0.5
├── hapi@15.1.1
├── hapi-auth-basic@4.2.0
├── hapi-auth-jwt2@7.2.0
├── hapi-error@1.5.0
├── hapi-mongo-models@6.0.0
├── hapi-node-postgres@4.0.1
├── hapi-sequelize@3.0.4
├── hapio@1.3.4
├── hoek@4.1.0
├── inert@4.0.2
├── jade@1.11.0
├── joi@9.1.0
├── jsonwebtoken@7.1.9
├── lab@11.1.0
├── lodash@4.16.6
├── lout@9.2.0
├── mongo-models@1.0.2
├── mongodb@2.2.10
├── node-uuid@1.4.7
├── nodemailer@2.6.4
├── nodemailer-markdown@1.0.1
├── nodemon@1.11.0
├── object-assign@4.1.0
├── pg@6.1.0
├── pg-hstore@2.3.2 extraneous
├── promptly@2.1.0
├── proxyquire@1.7.10
├── sequelize@3.25.1
├── slug@0.9.1
├── socket.io@1.5.0
├── vision@4.1.0
└── visionary@6.0.2
```

**Comment by kenhowardpdx** [comment]
@ADumaine take a look at #64. I ran into a similar issue.

**Comment by ADumaine** [comment]
I used that as a starting point but still could not get it to register as a plugin.

**Comment by alexdrans** [comment]
@ADumaine Check my reply on #64
