### ISSUE TITLE
Sequelize authenticate failure silenced

### ISSUE THREAD

**Issue by samudurand** [danecando/hapi-sequelize#71]
At the moment the plugin calls Sequelize ```authenticate()``` but does not handle the exception that might occur, resulting 404 route not found due to a silenced internal error. 

I got a fix for it (still need to write some tests for it), what is the process on this repo to propose a change ? Simply create a fork then PR  ?

**Comment by kenhowardpdx** [comment]
@samudurand I suggest you make the PR. Reference this issue you the commit/pull request.

**Comment by samudurand** [comment]
I have a branch ready but I made it from master, not knowing that there is a develop branch too, should I rebase against that one and make the PR against 'develop' ? Or would a PR against master suffice ?

**Comment by kenhowardpdx** [comment]
@samudurand I'm not a maintainer here but I'd do it against `master` as that's the branch used for release. It looks like `develop` is outdated.

**Comment by samudurand** [comment]
thanks for the advice :)

**Comment by samudurand** [comment]
Opened the PR under my other account
