### ISSUE TITLE
Plugin not detecting models

### ISSUE THREAD

**Issue by MrDHat** [danecando/hapi-sequelize#80]
I am using postgres with sequelize. Here is what my code looks like:

```js
server.register([
  {
    register: require('hapi-sequelizejs'), // eslint-disable-line global-require
    options: {
      name: Config.db.name,
      models: ['./models/*.js'],
      sequelize: new Sequelize(Config.db.name, Config.db.username, Config.db.password, {
        host: Config.db.host,
        dialect: 'postgres',
      }),
      sync: true,
    },
  },
])
```
When I log `req.server.plugins['hapi-sequelizejs'][Config.db.name].getModels()` I get an empty object. Here is what my model definition looks like:

```js
module.exports = (sequelize, DataTypes) => {
  const schema = {
    id: {
      type: DataTypes.UUIDV4,
      primaryKey: true,
    },
    name: DataTypes.STRING,
    email: DataTypes.STRING,
    gender: DataTypes.ENUM('male', 'female', 'other'),
  };
  return sequelize.define('User', schema);
};
```

Not sure what the problem is here. 

P.S. I have confirmed that the location of the models glob is correct by manually using `node-glob`.

**Comment by rogeriomq** [comment]
I have the same problem!

**Comment by MrDHat** [comment]
@rogeriomq https://github.com/valtlfelipe/hapi-sequelizejs/issues/4

**Comment by rogeriomq** [comment]
I solved with: 
`models: ['**/sequelize/models/**'],`
