### ISSUE TITLE
How about update hapi-sequelize to hapi 17 ?

### ISSUE THREAD

**Issue by mundodehads** [danecando/hapi-sequelize#87]
I've been thinking about update this package to work with hapi 17, but it'll be maintainded?
I see that the last commit was in 2016 and want to know for sure if I use the same code style or move to Standart... anyways, waiting for a discussion before jump right in to it, but thanks anyway for made this.

**Comment by valtlfelipe** [comment]
Hi @mundodehads 

I have a fork with major fixes, and support for the latest hapi and sequelize versions.
Please have a look at https://github.com/valtlfelipe/hapi-sequelizejs.

I'm doing my best to maintain it updated.

**Comment by mundodehads** [comment]
@valtlfelipe Olá, vi que você é brasileiro, estava cogitando refazer esse pacote, vou dar uma olhada no seu e ver se atende minha necessidade, qualquer posso tentar contribuir ou até mesmo compartilhar minhas ideias com você em uma issue no seu projeto.

Obrigado pela resposta.

**Comment by valtlfelipe** [comment]
@mundodehads Opa! Vamos conversar sim! Abre uma issue lá ou um PR 😄 

Abraços

**Comment by danecando** [comment]
#86 sorry about the inactivity thanks @valtlfelipe for his continued efforts. I'm going to start working on an update

**Comment by danecando** [comment]
Updated docs to refer users to hapi-sequelizejs thanks for the great work on the fork !
